### ISSUE TITLE
Trigger Event Support

### ISSUE THREAD

**Issue by Ashe** [schell/reflex-sdl2#10]
Just a quick one, I think that it'd be very helpful if Reflex-SDL allowed Trigger Events so that I could call the standard Reflex function `delay`. I know that reflex-sdl has it's own implementation, but it's not the easiest to use.

Thanks!

**Comment by schell** [comment]
You're right - the `Storable` constraint is a bummer. I'm a bit overwhelmed with my day job and other projects at the moment but this is on my radar. In the meantime I welcome any and all contributions!

**Comment by schell** [comment]
Just FYI - IIRC the standard `TriggerEventT` pattern isn't acceptable here. For example in `reflex-dom` a separate thread is used to poll a channel for new triggers, firing those triggers when appropriate. In `reflex-sdl2` events *should* be allowed to drive gl updates which have to happen on the main thread or the entire process crashes. Maybe we could simply make the main loop responsible for this. I feel like I tried that while originally authoring this library but I don't remember where I net out.

@ryantrinkle or @dalaing do you guys have any thoughts?

**Comment by Ashe** [comment]
I would try and help out a bit, but I'm still very new to Haskell and I'm not at the level of being able to understand the depth of the problem. I know its there as it's making me hit a wall, but I can't work out what's going on under the hood - ReflexSDL is kind of a lifesaver for me and allows me to learn FP without having to do the hard bit beforehand. I just thought I'd post this issue to flag it up, as I can imagine anyone making a game like myself who wishes to make a game would love to use delayed events at some point without creating timers everywhere!

**Comment by schell** [comment]
I think I have a fairly workable solution in https://github.com/schell/reflex-sdl2/pull/12. What we lose with this, is the ability to pause the main loop and wait for sdl events. Previously if there were no listeners waiting for ticks and there were no sdl events the main loop would block and wait for an event. This keeps the CPU use to a minimum. Now that we have trigger events we have to poll them often, so we can't wait for sdl events and must poll. It's probably fine though.

**Comment by akhra** [comment]
As long as the polling can be made conditional on having something to poll for, this comes down to a decision on the part of the programmer. Not sure I like the trade-off if it's mandatory tho.

**Comment by schell** [comment]
@tejon the other solution would be to do something like

```haskell
fix $ loop -> do
  eTrigsOrSDLs <- waitEither waitForTriggeredEvents waitForSDLEventsOrTicks
  either fireTriggered fireSDL eTrigsOrSDLs
  loop
```

... actually I think that would work quite nicely. Thoughts?

**Comment by schell** [comment]
Of course life is never as simple as it should be (from [SDL_WaitEvent](https://wiki.libsdl.org/SDL_WaitEvent) docs):
> As this function implicitly calls SDL_PumpEvents(), you can only call this function in the thread that initialized the video subsystem. 

So `waitForSDLEventsOrTicks` must run in the main thread.

**Comment by schell** [comment]
So I guess this is the reason I decided to push delayed events through SDL's event queue and hence the `Storable a` requirement. Maybe there's another way to push triggered events into the SDL queue from the other thread though. Then the main loop wouldn't change much.

**Comment by schell** [comment]
Okay I think I figured it out. First we register a new sdl user event with a reserved code, then we spawn a separate thread for blocking and reading out triggered events from the chan. When `chan` has triggers we push them into a `TVar` and then push a user event to wake sdl's `waitEvent`. Then in the main loop we check the payload of any `UserEvent`s for the reserved code and if it matches we read out the triggers, fire them and clean up.

**Comment by schell** [comment]
Okay - this is implemented in https://github.com/schell/reflex-sdl2/pull/12. The only problem I have with it is the arbitrary `reservedCode`. I can't think of a good way to keep down code collisions. What's the standard practice in SDL?

**Comment by Ashe** [comment]
Sorry that I haven't been able to respond but it looks like you've handled it :) 

As for whether this will go into the main loop and stuff - I don't know what SDL programs work without using the main loop but I'm under the impression that any sort of animation will need it for the time between frames. I'm probably mistaken as I'm fairly new to all this, but I think that more people will appreciate having delays than people will appreciate not using the main loop if that makes sense. Not my project and I'm glad you're working hard on it, so just my thoughts! :)

**Comment by schell** [comment]
TriggerEvent support added.
