### ISSUE TITLE
GHC 9.2 (and above) support

### ISSUE THREAD

**Issue by DrewFenwick** [schell/reflex-sdl2#25]
The dependency upper bounds are getting a touch old. 

I tried to build under GHC 9.2.4 but couldn't get a build plan. However when compiling with `--allow-newer` everything compiled without issue. 
I haven't tested, so it isn't certain to actually *work* with `--allow-newer` on, but still it's a promising sign that the only issue may just be over-restrictive bounds.

**Comment by schell** [comment]
I'm not working in Haskell anymore and don't have a lot of extra time on my hands - would you be willing to take maintainership of this library?

**Comment by schell** [comment]
This issue should be fixed with the latest hackage release.
