### ISSUE TITLE
Release tag missing from Git repository

### ISSUE THREAD

**Issue by andersk** [schell/reflex-sdl2#7]
There should be a v0.1.0.0 tag at 8f7f5547c76a81f98ee544be9e22a6ddcc9d9181, to make it easier to see what’s changed here since the version on Hackage, if nothing else.

**Comment by schell** [comment]
Thanks, I'll do that.

By the way - I've seen a couple of these notices come in today from you @andersk. What are you doing? Simple good samaritan stuff or do you have a project that's touching all this?

**Comment by andersk** [comment]
I have a game project in mind, and I’m still investigating frameworks I might want to use. It seems many of the relevant libraries are still undergoing rapid changes, and these tag requests are a hopefully helpful side effect of my trying to understand what’s going on.

**Comment by schell** [comment]
That's great to hear! Have you visited the #haskell-game channel on irc.freenode.net? It's not extremely active these days but a lot of really helpful and knowledgeable people lurk there.

**Comment by schell** [comment]
I've released a tag for `reflex-sdl2`. 

@andersk If your game uses 2d maps you should check out [Tiled](http://www.mapeditor.org/) as well as some new aeson instances for tiled types that I just wrote, [aeson-tiled](/schell/aeson-tiled), which will replace the current [htiled](/chrra/htiled). `htiled` uses `hxt` and is hard (for me) to maintain as there's a lot of Arrows cruft.
